INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_SOAPY_SDR SoapySDR)

FIND_PATH(
    SOAPY_SDR_INCLUDE_DIRS
    NAMES SoapySDR/Config.hpp
    HINTS $ENV{SOAPY_SDR_DIR}/include
        ${PC_SOAPY_SDR_INCLUDEDIR}
    PATHS /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    SOAPY_SDR_LIBRARIES
    NAMES SoapySDR SoapySDRd
    HINTS $ENV{SOAPY_SDR_DIR}/lib
        ${PC_SOAPY_SDR_LIBDIR}
    PATHS /usr/local/lib
          /usr/lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SOAPY_SDR DEFAULT_MSG SOAPY_SDR_LIBRARIES SOAPY_SDR_INCLUDE_DIRS)
MARK_AS_ADVANCED(SOAPY_SDR_LIBRARIES SOAPY_SDR_INCLUDE_DIRS)
