
// NO INCLUDE GUARDS, THE HEADER IS INTENDED FOR MULTIPLE INCLUSION

// Copyright Aleksey Gurtovoy 2002-2004
//
// Distributed under the Boost Software License, Version 1.0. 
// (See accompanying file LICENSE_1_0.txt or copy at 
// http://www.boost.org/LICENSE_1_0.txt)

// $Source$
// $Date: 2011-10-09 15:28:33 -0700 (Sun, 09 Oct 2011) $
// $Revision: 74865 $

#undef POTHOS_TT_AUX_BOOL_TRAIT_VALUE_DECL
#undef POTHOS_TT_AUX_BOOL_C_BASE
#undef POTHOS_TT_AUX_BOOL_TRAIT_DEF1
#undef POTHOS_TT_AUX_BOOL_TRAIT_DEF2
#undef POTHOS_TT_AUX_BOOL_TRAIT_DEF3
#undef POTHOS_TT_AUX_BOOL_TRAIT_SPEC1
#undef POTHOS_TT_AUX_BOOL_TRAIT_SPEC2
#undef POTHOS_TT_AUX_BOOL_TRAIT_IMPL_SPEC1
#undef POTHOS_TT_AUX_BOOL_TRAIT_IMPL_SPEC2
#undef POTHOS_TT_AUX_BOOL_TRAIT_PARTIAL_SPEC1_1
#undef POTHOS_TT_AUX_BOOL_TRAIT_PARTIAL_SPEC1_2
#undef POTHOS_TT_AUX_BOOL_TRAIT_PARTIAL_SPEC2_1
#undef POTHOS_TT_AUX_BOOL_TRAIT_PARTIAL_SPEC2_2
#undef POTHOS_TT_AUX_BOOL_TRAIT_IMPL_PARTIAL_SPEC2_1
#undef POTHOS_TT_AUX_BOOL_TRAIT_CV_SPEC1
