#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo -n "Install Pothos GUI icon resources...	"
if [ -x /usr/bin/xdg-icon-resource ] ; then
    for theme in hicolor gnome; do
        xdg-icon-resource install --noupdate --context mimetypes --theme ${theme} --size 128 ${DIR}/../icons/PothosGui.png application-pothos-gui || true
        xdg-icon-resource install --noupdate --context apps --theme ${theme} --size 128 ${DIR}/../icons/PothosGui.png pothos-gui || true
    done
    xdg-icon-resource forceupdate || true
    echo "OK"
else
    echo "FAIL (missing xdg-icon-resource)"
fi

echo -n "Install Pothos GUI MIME types...	"
if [ -x /usr/bin/xdg-mime ] ; then
    xdg-mime install ${DIR}/pothos-gui.xml || true
    echo "OK"
else
    echo "FAIL (missing xdg-mime)"
fi

echo -n "Install Pothos GUI menu launcher...	"
if [ -x /usr/bin/xdg-desktop-menu ] ; then
    xdg-desktop-menu install ${DIR}/pothos-gui.desktop || true
    echo "OK"
else
    echo "FAIL (missing xdg-desktop-menu)"
fi
