# /* **************************************************************************
#  *                                                                          *
#  *     (C) Copyright Paul Mensonides 2002.
#  *     Distributed under the Boost Software License, Version 1.0. (See
#  *     accompanying file LICENSE_1_0.txt or copy at
#  *     http://www.boost.org/LICENSE_1_0.txt)
#  *                                                                          *
#  ************************************************************************** */
#
# /* See http://www.boost.org for most recent version. */
#
# ifndef POTHOS_PREPROCESSOR_SEQ_ELEM_HPP
# define POTHOS_PREPROCESSOR_SEQ_ELEM_HPP
#
# include <Pothos/serialization/impl/preprocessor/cat.hpp>
# include <Pothos/serialization/impl/preprocessor/config/config.hpp>
# include <Pothos/serialization/impl/preprocessor/facilities/empty.hpp>
#
# /* POTHOS_PP_SEQ_ELEM */
#
# if ~POTHOS_PP_CONFIG_FLAGS() & POTHOS_PP_CONFIG_MWCC()
#    define POTHOS_PP_SEQ_ELEM(i, seq) POTHOS_PP_SEQ_ELEM_I(i, seq)
# else
#    define POTHOS_PP_SEQ_ELEM(i, seq) POTHOS_PP_SEQ_ELEM_I((i, seq))
# endif
#
# if POTHOS_PP_CONFIG_FLAGS() & POTHOS_PP_CONFIG_MSVC()
#    define POTHOS_PP_SEQ_ELEM_I(i, seq) POTHOS_PP_SEQ_ELEM_II((POTHOS_PP_SEQ_ELEM_ ## i seq))
#    define POTHOS_PP_SEQ_ELEM_II(res) POTHOS_PP_SEQ_ELEM_IV(POTHOS_PP_SEQ_ELEM_III res)
#    define POTHOS_PP_SEQ_ELEM_III(x, _) x POTHOS_PP_EMPTY()
#    define POTHOS_PP_SEQ_ELEM_IV(x) x
# elif POTHOS_PP_CONFIG_FLAGS() & POTHOS_PP_CONFIG_MWCC()
#    define POTHOS_PP_SEQ_ELEM_I(par) POTHOS_PP_SEQ_ELEM_II ## par
#    define POTHOS_PP_SEQ_ELEM_II(i, seq) POTHOS_PP_SEQ_ELEM_III(POTHOS_PP_SEQ_ELEM_ ## i ## seq)
#    define POTHOS_PP_SEQ_ELEM_III(im) POTHOS_PP_SEQ_ELEM_IV(im)
#    define POTHOS_PP_SEQ_ELEM_IV(x, _) x
# else
#    if defined(__IBMC__) || defined(__IBMCPP__)
#        define POTHOS_PP_SEQ_ELEM_I(i, seq) POTHOS_PP_SEQ_ELEM_II(POTHOS_PP_CAT(POTHOS_PP_SEQ_ELEM_ ## i, seq))
#    else
#        define POTHOS_PP_SEQ_ELEM_I(i, seq) POTHOS_PP_SEQ_ELEM_II(POTHOS_PP_SEQ_ELEM_ ## i seq)
#    endif
#    define POTHOS_PP_SEQ_ELEM_II(im) POTHOS_PP_SEQ_ELEM_III(im)
#    define POTHOS_PP_SEQ_ELEM_III(x, _) x
# endif
#
# define POTHOS_PP_SEQ_ELEM_0(x) x, POTHOS_PP_NIL
# define POTHOS_PP_SEQ_ELEM_1(_) POTHOS_PP_SEQ_ELEM_0
# define POTHOS_PP_SEQ_ELEM_2(_) POTHOS_PP_SEQ_ELEM_1
# define POTHOS_PP_SEQ_ELEM_3(_) POTHOS_PP_SEQ_ELEM_2
# define POTHOS_PP_SEQ_ELEM_4(_) POTHOS_PP_SEQ_ELEM_3
# define POTHOS_PP_SEQ_ELEM_5(_) POTHOS_PP_SEQ_ELEM_4
# define POTHOS_PP_SEQ_ELEM_6(_) POTHOS_PP_SEQ_ELEM_5
# define POTHOS_PP_SEQ_ELEM_7(_) POTHOS_PP_SEQ_ELEM_6
# define POTHOS_PP_SEQ_ELEM_8(_) POTHOS_PP_SEQ_ELEM_7
# define POTHOS_PP_SEQ_ELEM_9(_) POTHOS_PP_SEQ_ELEM_8
# define POTHOS_PP_SEQ_ELEM_10(_) POTHOS_PP_SEQ_ELEM_9
# define POTHOS_PP_SEQ_ELEM_11(_) POTHOS_PP_SEQ_ELEM_10
# define POTHOS_PP_SEQ_ELEM_12(_) POTHOS_PP_SEQ_ELEM_11
# define POTHOS_PP_SEQ_ELEM_13(_) POTHOS_PP_SEQ_ELEM_12
# define POTHOS_PP_SEQ_ELEM_14(_) POTHOS_PP_SEQ_ELEM_13
# define POTHOS_PP_SEQ_ELEM_15(_) POTHOS_PP_SEQ_ELEM_14
# define POTHOS_PP_SEQ_ELEM_16(_) POTHOS_PP_SEQ_ELEM_15
# define POTHOS_PP_SEQ_ELEM_17(_) POTHOS_PP_SEQ_ELEM_16
# define POTHOS_PP_SEQ_ELEM_18(_) POTHOS_PP_SEQ_ELEM_17
# define POTHOS_PP_SEQ_ELEM_19(_) POTHOS_PP_SEQ_ELEM_18
# define POTHOS_PP_SEQ_ELEM_20(_) POTHOS_PP_SEQ_ELEM_19
# define POTHOS_PP_SEQ_ELEM_21(_) POTHOS_PP_SEQ_ELEM_20
# define POTHOS_PP_SEQ_ELEM_22(_) POTHOS_PP_SEQ_ELEM_21
# define POTHOS_PP_SEQ_ELEM_23(_) POTHOS_PP_SEQ_ELEM_22
# define POTHOS_PP_SEQ_ELEM_24(_) POTHOS_PP_SEQ_ELEM_23
# define POTHOS_PP_SEQ_ELEM_25(_) POTHOS_PP_SEQ_ELEM_24
# define POTHOS_PP_SEQ_ELEM_26(_) POTHOS_PP_SEQ_ELEM_25
# define POTHOS_PP_SEQ_ELEM_27(_) POTHOS_PP_SEQ_ELEM_26
# define POTHOS_PP_SEQ_ELEM_28(_) POTHOS_PP_SEQ_ELEM_27
# define POTHOS_PP_SEQ_ELEM_29(_) POTHOS_PP_SEQ_ELEM_28
# define POTHOS_PP_SEQ_ELEM_30(_) POTHOS_PP_SEQ_ELEM_29
# define POTHOS_PP_SEQ_ELEM_31(_) POTHOS_PP_SEQ_ELEM_30
# define POTHOS_PP_SEQ_ELEM_32(_) POTHOS_PP_SEQ_ELEM_31
# define POTHOS_PP_SEQ_ELEM_33(_) POTHOS_PP_SEQ_ELEM_32
# define POTHOS_PP_SEQ_ELEM_34(_) POTHOS_PP_SEQ_ELEM_33
# define POTHOS_PP_SEQ_ELEM_35(_) POTHOS_PP_SEQ_ELEM_34
# define POTHOS_PP_SEQ_ELEM_36(_) POTHOS_PP_SEQ_ELEM_35
# define POTHOS_PP_SEQ_ELEM_37(_) POTHOS_PP_SEQ_ELEM_36
# define POTHOS_PP_SEQ_ELEM_38(_) POTHOS_PP_SEQ_ELEM_37
# define POTHOS_PP_SEQ_ELEM_39(_) POTHOS_PP_SEQ_ELEM_38
# define POTHOS_PP_SEQ_ELEM_40(_) POTHOS_PP_SEQ_ELEM_39
# define POTHOS_PP_SEQ_ELEM_41(_) POTHOS_PP_SEQ_ELEM_40
# define POTHOS_PP_SEQ_ELEM_42(_) POTHOS_PP_SEQ_ELEM_41
# define POTHOS_PP_SEQ_ELEM_43(_) POTHOS_PP_SEQ_ELEM_42
# define POTHOS_PP_SEQ_ELEM_44(_) POTHOS_PP_SEQ_ELEM_43
# define POTHOS_PP_SEQ_ELEM_45(_) POTHOS_PP_SEQ_ELEM_44
# define POTHOS_PP_SEQ_ELEM_46(_) POTHOS_PP_SEQ_ELEM_45
# define POTHOS_PP_SEQ_ELEM_47(_) POTHOS_PP_SEQ_ELEM_46
# define POTHOS_PP_SEQ_ELEM_48(_) POTHOS_PP_SEQ_ELEM_47
# define POTHOS_PP_SEQ_ELEM_49(_) POTHOS_PP_SEQ_ELEM_48
# define POTHOS_PP_SEQ_ELEM_50(_) POTHOS_PP_SEQ_ELEM_49
# define POTHOS_PP_SEQ_ELEM_51(_) POTHOS_PP_SEQ_ELEM_50
# define POTHOS_PP_SEQ_ELEM_52(_) POTHOS_PP_SEQ_ELEM_51
# define POTHOS_PP_SEQ_ELEM_53(_) POTHOS_PP_SEQ_ELEM_52
# define POTHOS_PP_SEQ_ELEM_54(_) POTHOS_PP_SEQ_ELEM_53
# define POTHOS_PP_SEQ_ELEM_55(_) POTHOS_PP_SEQ_ELEM_54
# define POTHOS_PP_SEQ_ELEM_56(_) POTHOS_PP_SEQ_ELEM_55
# define POTHOS_PP_SEQ_ELEM_57(_) POTHOS_PP_SEQ_ELEM_56
# define POTHOS_PP_SEQ_ELEM_58(_) POTHOS_PP_SEQ_ELEM_57
# define POTHOS_PP_SEQ_ELEM_59(_) POTHOS_PP_SEQ_ELEM_58
# define POTHOS_PP_SEQ_ELEM_60(_) POTHOS_PP_SEQ_ELEM_59
# define POTHOS_PP_SEQ_ELEM_61(_) POTHOS_PP_SEQ_ELEM_60
# define POTHOS_PP_SEQ_ELEM_62(_) POTHOS_PP_SEQ_ELEM_61
# define POTHOS_PP_SEQ_ELEM_63(_) POTHOS_PP_SEQ_ELEM_62
# define POTHOS_PP_SEQ_ELEM_64(_) POTHOS_PP_SEQ_ELEM_63
# define POTHOS_PP_SEQ_ELEM_65(_) POTHOS_PP_SEQ_ELEM_64
# define POTHOS_PP_SEQ_ELEM_66(_) POTHOS_PP_SEQ_ELEM_65
# define POTHOS_PP_SEQ_ELEM_67(_) POTHOS_PP_SEQ_ELEM_66
# define POTHOS_PP_SEQ_ELEM_68(_) POTHOS_PP_SEQ_ELEM_67
# define POTHOS_PP_SEQ_ELEM_69(_) POTHOS_PP_SEQ_ELEM_68
# define POTHOS_PP_SEQ_ELEM_70(_) POTHOS_PP_SEQ_ELEM_69
# define POTHOS_PP_SEQ_ELEM_71(_) POTHOS_PP_SEQ_ELEM_70
# define POTHOS_PP_SEQ_ELEM_72(_) POTHOS_PP_SEQ_ELEM_71
# define POTHOS_PP_SEQ_ELEM_73(_) POTHOS_PP_SEQ_ELEM_72
# define POTHOS_PP_SEQ_ELEM_74(_) POTHOS_PP_SEQ_ELEM_73
# define POTHOS_PP_SEQ_ELEM_75(_) POTHOS_PP_SEQ_ELEM_74
# define POTHOS_PP_SEQ_ELEM_76(_) POTHOS_PP_SEQ_ELEM_75
# define POTHOS_PP_SEQ_ELEM_77(_) POTHOS_PP_SEQ_ELEM_76
# define POTHOS_PP_SEQ_ELEM_78(_) POTHOS_PP_SEQ_ELEM_77
# define POTHOS_PP_SEQ_ELEM_79(_) POTHOS_PP_SEQ_ELEM_78
# define POTHOS_PP_SEQ_ELEM_80(_) POTHOS_PP_SEQ_ELEM_79
# define POTHOS_PP_SEQ_ELEM_81(_) POTHOS_PP_SEQ_ELEM_80
# define POTHOS_PP_SEQ_ELEM_82(_) POTHOS_PP_SEQ_ELEM_81
# define POTHOS_PP_SEQ_ELEM_83(_) POTHOS_PP_SEQ_ELEM_82
# define POTHOS_PP_SEQ_ELEM_84(_) POTHOS_PP_SEQ_ELEM_83
# define POTHOS_PP_SEQ_ELEM_85(_) POTHOS_PP_SEQ_ELEM_84
# define POTHOS_PP_SEQ_ELEM_86(_) POTHOS_PP_SEQ_ELEM_85
# define POTHOS_PP_SEQ_ELEM_87(_) POTHOS_PP_SEQ_ELEM_86
# define POTHOS_PP_SEQ_ELEM_88(_) POTHOS_PP_SEQ_ELEM_87
# define POTHOS_PP_SEQ_ELEM_89(_) POTHOS_PP_SEQ_ELEM_88
# define POTHOS_PP_SEQ_ELEM_90(_) POTHOS_PP_SEQ_ELEM_89
# define POTHOS_PP_SEQ_ELEM_91(_) POTHOS_PP_SEQ_ELEM_90
# define POTHOS_PP_SEQ_ELEM_92(_) POTHOS_PP_SEQ_ELEM_91
# define POTHOS_PP_SEQ_ELEM_93(_) POTHOS_PP_SEQ_ELEM_92
# define POTHOS_PP_SEQ_ELEM_94(_) POTHOS_PP_SEQ_ELEM_93
# define POTHOS_PP_SEQ_ELEM_95(_) POTHOS_PP_SEQ_ELEM_94
# define POTHOS_PP_SEQ_ELEM_96(_) POTHOS_PP_SEQ_ELEM_95
# define POTHOS_PP_SEQ_ELEM_97(_) POTHOS_PP_SEQ_ELEM_96
# define POTHOS_PP_SEQ_ELEM_98(_) POTHOS_PP_SEQ_ELEM_97
# define POTHOS_PP_SEQ_ELEM_99(_) POTHOS_PP_SEQ_ELEM_98
# define POTHOS_PP_SEQ_ELEM_100(_) POTHOS_PP_SEQ_ELEM_99
# define POTHOS_PP_SEQ_ELEM_101(_) POTHOS_PP_SEQ_ELEM_100
# define POTHOS_PP_SEQ_ELEM_102(_) POTHOS_PP_SEQ_ELEM_101
# define POTHOS_PP_SEQ_ELEM_103(_) POTHOS_PP_SEQ_ELEM_102
# define POTHOS_PP_SEQ_ELEM_104(_) POTHOS_PP_SEQ_ELEM_103
# define POTHOS_PP_SEQ_ELEM_105(_) POTHOS_PP_SEQ_ELEM_104
# define POTHOS_PP_SEQ_ELEM_106(_) POTHOS_PP_SEQ_ELEM_105
# define POTHOS_PP_SEQ_ELEM_107(_) POTHOS_PP_SEQ_ELEM_106
# define POTHOS_PP_SEQ_ELEM_108(_) POTHOS_PP_SEQ_ELEM_107
# define POTHOS_PP_SEQ_ELEM_109(_) POTHOS_PP_SEQ_ELEM_108
# define POTHOS_PP_SEQ_ELEM_110(_) POTHOS_PP_SEQ_ELEM_109
# define POTHOS_PP_SEQ_ELEM_111(_) POTHOS_PP_SEQ_ELEM_110
# define POTHOS_PP_SEQ_ELEM_112(_) POTHOS_PP_SEQ_ELEM_111
# define POTHOS_PP_SEQ_ELEM_113(_) POTHOS_PP_SEQ_ELEM_112
# define POTHOS_PP_SEQ_ELEM_114(_) POTHOS_PP_SEQ_ELEM_113
# define POTHOS_PP_SEQ_ELEM_115(_) POTHOS_PP_SEQ_ELEM_114
# define POTHOS_PP_SEQ_ELEM_116(_) POTHOS_PP_SEQ_ELEM_115
# define POTHOS_PP_SEQ_ELEM_117(_) POTHOS_PP_SEQ_ELEM_116
# define POTHOS_PP_SEQ_ELEM_118(_) POTHOS_PP_SEQ_ELEM_117
# define POTHOS_PP_SEQ_ELEM_119(_) POTHOS_PP_SEQ_ELEM_118
# define POTHOS_PP_SEQ_ELEM_120(_) POTHOS_PP_SEQ_ELEM_119
# define POTHOS_PP_SEQ_ELEM_121(_) POTHOS_PP_SEQ_ELEM_120
# define POTHOS_PP_SEQ_ELEM_122(_) POTHOS_PP_SEQ_ELEM_121
# define POTHOS_PP_SEQ_ELEM_123(_) POTHOS_PP_SEQ_ELEM_122
# define POTHOS_PP_SEQ_ELEM_124(_) POTHOS_PP_SEQ_ELEM_123
# define POTHOS_PP_SEQ_ELEM_125(_) POTHOS_PP_SEQ_ELEM_124
# define POTHOS_PP_SEQ_ELEM_126(_) POTHOS_PP_SEQ_ELEM_125
# define POTHOS_PP_SEQ_ELEM_127(_) POTHOS_PP_SEQ_ELEM_126
# define POTHOS_PP_SEQ_ELEM_128(_) POTHOS_PP_SEQ_ELEM_127
# define POTHOS_PP_SEQ_ELEM_129(_) POTHOS_PP_SEQ_ELEM_128
# define POTHOS_PP_SEQ_ELEM_130(_) POTHOS_PP_SEQ_ELEM_129
# define POTHOS_PP_SEQ_ELEM_131(_) POTHOS_PP_SEQ_ELEM_130
# define POTHOS_PP_SEQ_ELEM_132(_) POTHOS_PP_SEQ_ELEM_131
# define POTHOS_PP_SEQ_ELEM_133(_) POTHOS_PP_SEQ_ELEM_132
# define POTHOS_PP_SEQ_ELEM_134(_) POTHOS_PP_SEQ_ELEM_133
# define POTHOS_PP_SEQ_ELEM_135(_) POTHOS_PP_SEQ_ELEM_134
# define POTHOS_PP_SEQ_ELEM_136(_) POTHOS_PP_SEQ_ELEM_135
# define POTHOS_PP_SEQ_ELEM_137(_) POTHOS_PP_SEQ_ELEM_136
# define POTHOS_PP_SEQ_ELEM_138(_) POTHOS_PP_SEQ_ELEM_137
# define POTHOS_PP_SEQ_ELEM_139(_) POTHOS_PP_SEQ_ELEM_138
# define POTHOS_PP_SEQ_ELEM_140(_) POTHOS_PP_SEQ_ELEM_139
# define POTHOS_PP_SEQ_ELEM_141(_) POTHOS_PP_SEQ_ELEM_140
# define POTHOS_PP_SEQ_ELEM_142(_) POTHOS_PP_SEQ_ELEM_141
# define POTHOS_PP_SEQ_ELEM_143(_) POTHOS_PP_SEQ_ELEM_142
# define POTHOS_PP_SEQ_ELEM_144(_) POTHOS_PP_SEQ_ELEM_143
# define POTHOS_PP_SEQ_ELEM_145(_) POTHOS_PP_SEQ_ELEM_144
# define POTHOS_PP_SEQ_ELEM_146(_) POTHOS_PP_SEQ_ELEM_145
# define POTHOS_PP_SEQ_ELEM_147(_) POTHOS_PP_SEQ_ELEM_146
# define POTHOS_PP_SEQ_ELEM_148(_) POTHOS_PP_SEQ_ELEM_147
# define POTHOS_PP_SEQ_ELEM_149(_) POTHOS_PP_SEQ_ELEM_148
# define POTHOS_PP_SEQ_ELEM_150(_) POTHOS_PP_SEQ_ELEM_149
# define POTHOS_PP_SEQ_ELEM_151(_) POTHOS_PP_SEQ_ELEM_150
# define POTHOS_PP_SEQ_ELEM_152(_) POTHOS_PP_SEQ_ELEM_151
# define POTHOS_PP_SEQ_ELEM_153(_) POTHOS_PP_SEQ_ELEM_152
# define POTHOS_PP_SEQ_ELEM_154(_) POTHOS_PP_SEQ_ELEM_153
# define POTHOS_PP_SEQ_ELEM_155(_) POTHOS_PP_SEQ_ELEM_154
# define POTHOS_PP_SEQ_ELEM_156(_) POTHOS_PP_SEQ_ELEM_155
# define POTHOS_PP_SEQ_ELEM_157(_) POTHOS_PP_SEQ_ELEM_156
# define POTHOS_PP_SEQ_ELEM_158(_) POTHOS_PP_SEQ_ELEM_157
# define POTHOS_PP_SEQ_ELEM_159(_) POTHOS_PP_SEQ_ELEM_158
# define POTHOS_PP_SEQ_ELEM_160(_) POTHOS_PP_SEQ_ELEM_159
# define POTHOS_PP_SEQ_ELEM_161(_) POTHOS_PP_SEQ_ELEM_160
# define POTHOS_PP_SEQ_ELEM_162(_) POTHOS_PP_SEQ_ELEM_161
# define POTHOS_PP_SEQ_ELEM_163(_) POTHOS_PP_SEQ_ELEM_162
# define POTHOS_PP_SEQ_ELEM_164(_) POTHOS_PP_SEQ_ELEM_163
# define POTHOS_PP_SEQ_ELEM_165(_) POTHOS_PP_SEQ_ELEM_164
# define POTHOS_PP_SEQ_ELEM_166(_) POTHOS_PP_SEQ_ELEM_165
# define POTHOS_PP_SEQ_ELEM_167(_) POTHOS_PP_SEQ_ELEM_166
# define POTHOS_PP_SEQ_ELEM_168(_) POTHOS_PP_SEQ_ELEM_167
# define POTHOS_PP_SEQ_ELEM_169(_) POTHOS_PP_SEQ_ELEM_168
# define POTHOS_PP_SEQ_ELEM_170(_) POTHOS_PP_SEQ_ELEM_169
# define POTHOS_PP_SEQ_ELEM_171(_) POTHOS_PP_SEQ_ELEM_170
# define POTHOS_PP_SEQ_ELEM_172(_) POTHOS_PP_SEQ_ELEM_171
# define POTHOS_PP_SEQ_ELEM_173(_) POTHOS_PP_SEQ_ELEM_172
# define POTHOS_PP_SEQ_ELEM_174(_) POTHOS_PP_SEQ_ELEM_173
# define POTHOS_PP_SEQ_ELEM_175(_) POTHOS_PP_SEQ_ELEM_174
# define POTHOS_PP_SEQ_ELEM_176(_) POTHOS_PP_SEQ_ELEM_175
# define POTHOS_PP_SEQ_ELEM_177(_) POTHOS_PP_SEQ_ELEM_176
# define POTHOS_PP_SEQ_ELEM_178(_) POTHOS_PP_SEQ_ELEM_177
# define POTHOS_PP_SEQ_ELEM_179(_) POTHOS_PP_SEQ_ELEM_178
# define POTHOS_PP_SEQ_ELEM_180(_) POTHOS_PP_SEQ_ELEM_179
# define POTHOS_PP_SEQ_ELEM_181(_) POTHOS_PP_SEQ_ELEM_180
# define POTHOS_PP_SEQ_ELEM_182(_) POTHOS_PP_SEQ_ELEM_181
# define POTHOS_PP_SEQ_ELEM_183(_) POTHOS_PP_SEQ_ELEM_182
# define POTHOS_PP_SEQ_ELEM_184(_) POTHOS_PP_SEQ_ELEM_183
# define POTHOS_PP_SEQ_ELEM_185(_) POTHOS_PP_SEQ_ELEM_184
# define POTHOS_PP_SEQ_ELEM_186(_) POTHOS_PP_SEQ_ELEM_185
# define POTHOS_PP_SEQ_ELEM_187(_) POTHOS_PP_SEQ_ELEM_186
# define POTHOS_PP_SEQ_ELEM_188(_) POTHOS_PP_SEQ_ELEM_187
# define POTHOS_PP_SEQ_ELEM_189(_) POTHOS_PP_SEQ_ELEM_188
# define POTHOS_PP_SEQ_ELEM_190(_) POTHOS_PP_SEQ_ELEM_189
# define POTHOS_PP_SEQ_ELEM_191(_) POTHOS_PP_SEQ_ELEM_190
# define POTHOS_PP_SEQ_ELEM_192(_) POTHOS_PP_SEQ_ELEM_191
# define POTHOS_PP_SEQ_ELEM_193(_) POTHOS_PP_SEQ_ELEM_192
# define POTHOS_PP_SEQ_ELEM_194(_) POTHOS_PP_SEQ_ELEM_193
# define POTHOS_PP_SEQ_ELEM_195(_) POTHOS_PP_SEQ_ELEM_194
# define POTHOS_PP_SEQ_ELEM_196(_) POTHOS_PP_SEQ_ELEM_195
# define POTHOS_PP_SEQ_ELEM_197(_) POTHOS_PP_SEQ_ELEM_196
# define POTHOS_PP_SEQ_ELEM_198(_) POTHOS_PP_SEQ_ELEM_197
# define POTHOS_PP_SEQ_ELEM_199(_) POTHOS_PP_SEQ_ELEM_198
# define POTHOS_PP_SEQ_ELEM_200(_) POTHOS_PP_SEQ_ELEM_199
# define POTHOS_PP_SEQ_ELEM_201(_) POTHOS_PP_SEQ_ELEM_200
# define POTHOS_PP_SEQ_ELEM_202(_) POTHOS_PP_SEQ_ELEM_201
# define POTHOS_PP_SEQ_ELEM_203(_) POTHOS_PP_SEQ_ELEM_202
# define POTHOS_PP_SEQ_ELEM_204(_) POTHOS_PP_SEQ_ELEM_203
# define POTHOS_PP_SEQ_ELEM_205(_) POTHOS_PP_SEQ_ELEM_204
# define POTHOS_PP_SEQ_ELEM_206(_) POTHOS_PP_SEQ_ELEM_205
# define POTHOS_PP_SEQ_ELEM_207(_) POTHOS_PP_SEQ_ELEM_206
# define POTHOS_PP_SEQ_ELEM_208(_) POTHOS_PP_SEQ_ELEM_207
# define POTHOS_PP_SEQ_ELEM_209(_) POTHOS_PP_SEQ_ELEM_208
# define POTHOS_PP_SEQ_ELEM_210(_) POTHOS_PP_SEQ_ELEM_209
# define POTHOS_PP_SEQ_ELEM_211(_) POTHOS_PP_SEQ_ELEM_210
# define POTHOS_PP_SEQ_ELEM_212(_) POTHOS_PP_SEQ_ELEM_211
# define POTHOS_PP_SEQ_ELEM_213(_) POTHOS_PP_SEQ_ELEM_212
# define POTHOS_PP_SEQ_ELEM_214(_) POTHOS_PP_SEQ_ELEM_213
# define POTHOS_PP_SEQ_ELEM_215(_) POTHOS_PP_SEQ_ELEM_214
# define POTHOS_PP_SEQ_ELEM_216(_) POTHOS_PP_SEQ_ELEM_215
# define POTHOS_PP_SEQ_ELEM_217(_) POTHOS_PP_SEQ_ELEM_216
# define POTHOS_PP_SEQ_ELEM_218(_) POTHOS_PP_SEQ_ELEM_217
# define POTHOS_PP_SEQ_ELEM_219(_) POTHOS_PP_SEQ_ELEM_218
# define POTHOS_PP_SEQ_ELEM_220(_) POTHOS_PP_SEQ_ELEM_219
# define POTHOS_PP_SEQ_ELEM_221(_) POTHOS_PP_SEQ_ELEM_220
# define POTHOS_PP_SEQ_ELEM_222(_) POTHOS_PP_SEQ_ELEM_221
# define POTHOS_PP_SEQ_ELEM_223(_) POTHOS_PP_SEQ_ELEM_222
# define POTHOS_PP_SEQ_ELEM_224(_) POTHOS_PP_SEQ_ELEM_223
# define POTHOS_PP_SEQ_ELEM_225(_) POTHOS_PP_SEQ_ELEM_224
# define POTHOS_PP_SEQ_ELEM_226(_) POTHOS_PP_SEQ_ELEM_225
# define POTHOS_PP_SEQ_ELEM_227(_) POTHOS_PP_SEQ_ELEM_226
# define POTHOS_PP_SEQ_ELEM_228(_) POTHOS_PP_SEQ_ELEM_227
# define POTHOS_PP_SEQ_ELEM_229(_) POTHOS_PP_SEQ_ELEM_228
# define POTHOS_PP_SEQ_ELEM_230(_) POTHOS_PP_SEQ_ELEM_229
# define POTHOS_PP_SEQ_ELEM_231(_) POTHOS_PP_SEQ_ELEM_230
# define POTHOS_PP_SEQ_ELEM_232(_) POTHOS_PP_SEQ_ELEM_231
# define POTHOS_PP_SEQ_ELEM_233(_) POTHOS_PP_SEQ_ELEM_232
# define POTHOS_PP_SEQ_ELEM_234(_) POTHOS_PP_SEQ_ELEM_233
# define POTHOS_PP_SEQ_ELEM_235(_) POTHOS_PP_SEQ_ELEM_234
# define POTHOS_PP_SEQ_ELEM_236(_) POTHOS_PP_SEQ_ELEM_235
# define POTHOS_PP_SEQ_ELEM_237(_) POTHOS_PP_SEQ_ELEM_236
# define POTHOS_PP_SEQ_ELEM_238(_) POTHOS_PP_SEQ_ELEM_237
# define POTHOS_PP_SEQ_ELEM_239(_) POTHOS_PP_SEQ_ELEM_238
# define POTHOS_PP_SEQ_ELEM_240(_) POTHOS_PP_SEQ_ELEM_239
# define POTHOS_PP_SEQ_ELEM_241(_) POTHOS_PP_SEQ_ELEM_240
# define POTHOS_PP_SEQ_ELEM_242(_) POTHOS_PP_SEQ_ELEM_241
# define POTHOS_PP_SEQ_ELEM_243(_) POTHOS_PP_SEQ_ELEM_242
# define POTHOS_PP_SEQ_ELEM_244(_) POTHOS_PP_SEQ_ELEM_243
# define POTHOS_PP_SEQ_ELEM_245(_) POTHOS_PP_SEQ_ELEM_244
# define POTHOS_PP_SEQ_ELEM_246(_) POTHOS_PP_SEQ_ELEM_245
# define POTHOS_PP_SEQ_ELEM_247(_) POTHOS_PP_SEQ_ELEM_246
# define POTHOS_PP_SEQ_ELEM_248(_) POTHOS_PP_SEQ_ELEM_247
# define POTHOS_PP_SEQ_ELEM_249(_) POTHOS_PP_SEQ_ELEM_248
# define POTHOS_PP_SEQ_ELEM_250(_) POTHOS_PP_SEQ_ELEM_249
# define POTHOS_PP_SEQ_ELEM_251(_) POTHOS_PP_SEQ_ELEM_250
# define POTHOS_PP_SEQ_ELEM_252(_) POTHOS_PP_SEQ_ELEM_251
# define POTHOS_PP_SEQ_ELEM_253(_) POTHOS_PP_SEQ_ELEM_252
# define POTHOS_PP_SEQ_ELEM_254(_) POTHOS_PP_SEQ_ELEM_253
# define POTHOS_PP_SEQ_ELEM_255(_) POTHOS_PP_SEQ_ELEM_254
#
# endif
